### ISSUE TITLE
CSV Import - Chart Colour Validation

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#548]
Alas there was a side effect of validating the chart colour: Chart Colour isn't exported or imported in a DataPointVO's CSV. This means with a new templateXid all CSV imported points will have a null chart colour and fail to import.

**Comment by terrypacker** [comment]
Fixed by updating the model via the template prior to validation of the model.  This probably should have been being done anyway.  This is worth testing thoroughly as we also had an issue in the Core when editing points and changing the template after this change, this specific bug has been fixed.

**Comment by Puckfist** [comment]
Not resolved. Consider adding a default chart color next to the PlainRenderer for null templateXid conditions

**Comment by terrypacker** [comment]
This is ready for testing again with commit infiniteautomation/ma-modules-private@ecfc6c13a34f47b0477544166f27b1cd5bc86045

**Comment by Puckfist** [comment]
Resolved.
